# Generated by Django 5.2.11 on 2026-05-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Landlord'), ('3', 'Manager')], default='4', max_length=10),
        ),
    ]
